for count in range(1):
    print("__")
    print("/  \_")
    print(" /^    \ ")
    print("/  ^    \_")
    print("_/ ^ ^     ^\ ")
    print(" /  ^     ^    \ ")
    print(" __")
    print(" /  \_")
    print("/^    \ ")
    print("/  ^    \_ ")
    print("_/ ^ ^     ^\ ")
    print("/  ^     ^    \ ")
    print(" __")
    print(" /  \_")
    print("/^    \ ")
    print(" /  ^    \_")
    print("_/ ^ ^     ^\ ")
    print(" /  ^     ^    \ ")